# Generated by Django 4.1 on 2022-08-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
    ]
